"""Content contracts for the host-evidence errata and the install-version caliber.

Five pinned guarantees:

- Errata carrier: the route-decision archive ``completion-summary.md``
  carries the appended errata section (title, both dynamic-workflow run
  ids, the reproducible route-consistency caliber) while the original
  "not live-verified" statements survive untouched as period facts — the
  erratum is an addendum, never a rewrite of archive history.
- Notes carrier: the ``.spec/docs`` note carries both run ids, the runtime
  launch-header fact, and the version-caliber anchors (pyproject source of
  truth, ``stamp_build_info`` as the build-time-only VERSION writer).
- Version caliber: the note's claimed version equals the actual
  ``pyproject.toml`` version, and ``install.sh`` still has no VERSION
  logic — the caliber cannot silently regress into citing a VERSION file
  that tracked history never had.
- Carrier exclusivity: the full installed-copy VERSION path literal
  appears in git-searchable text only inside the docs note's
  irreproducible-caliber explanation.
- Self-scope: this module asserts nothing about the existence of untracked
  host run-script files (they are git-ignored and absent on fresh
  clones); the guards stay green out of the box.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

ARCHIVE_SUMMARY = ROOT / ".spec/specs/archive/2026-09-25_add-route-decision-table/completion-summary.md"
DOCS_NOTE = ROOT / ".spec/docs/2026-09-25_add-host-evidence-and-version-errata_host-parity-and-install-version-basis.md"
BUILD_RELEASE = ROOT / "scripts/build_release.py"
INSTALL_SH = ROOT / "install.sh"
PYPROJECT = ROOT / "pyproject.toml"

ERRATA_TITLE = "## 勘误补记（2026-09-25_add-host-evidence-and-version-errata）"
RUN_ID_A = "dwfrun-67ae9672-7e51-4e2f-b815-738ab842e501"
RUN_ID_B = "dwfrun-078db4ba-3e8c-4d26-9edb-f5431b18186a"
LAUNCH_HEADER = "Generated by @zcode/dynamic-workflow-runtime before every launch"
ROUTE_CONSISTENCY_CALIBER = "python3 -m pytest tests/test_route_cross_consistency.py -q"
ORIGINAL_STATEMENT = "宿主执行不进 pytest、未实测"

# Split concatenation keeps this module's own source free of the contiguous
# literal, so the exclusivity scan below never self-matches.
VERSION_PATH_LITERAL = "skills/spec/" + "VERSION"
RUNS_DIR_MARK = ".zc" + "ode"
RUNS_DIR_NAME = "workflow" + "-runs"


def _git_grep_paths(pattern: str) -> list[str]:
    result = subprocess.run(
        ["git", "grep", "-n", "--untracked", pattern, "--", "."],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode == 1:
        return []
    if result.returncode != 0:
        raise AssertionError(f"git grep failed unexpectedly: {result.stderr}")
    return [line.split(":", 1)[0] for line in result.stdout.splitlines()]


def test_archive_errata_section_is_additive() -> None:
    text = ARCHIVE_SUMMARY.read_text(encoding="utf-8")
    assert text.count("## 问题处置") == 1
    assert ERRATA_TITLE in text
    assert text.index("## 问题处置") < text.index(ERRATA_TITLE)
    # The original statements survive as period facts: the erratum appends,
    # it never rewrites archive history.
    assert text.count(ORIGINAL_STATEMENT) >= 2


def test_archive_errata_carries_host_and_reproducible_evidence() -> None:
    text = ARCHIVE_SUMMARY.read_text(encoding="utf-8")
    for run_id in (RUN_ID_A, RUN_ID_B):
        assert run_id in text
    assert LAUNCH_HEADER in text
    assert ROUTE_CONSISTENCY_CALIBER in text
    assert "12 passed" in text


def test_docs_note_carries_run_and_version_anchors() -> None:
    text = DOCS_NOTE.read_text(encoding="utf-8")
    for run_id in (RUN_ID_A, RUN_ID_B):
        assert run_id in text
    assert LAUNCH_HEADER in text
    assert "pyproject.toml" in text
    assert "stamp_build_info" in text
    # The build-time-only VERSION writer the note cites stays real in source.
    build_source = BUILD_RELEASE.read_text(encoding="utf-8")
    assert "def stamp_build_info" in build_source
    assert '(runtime_dir / "VERSION").write_text' in build_source


def test_note_version_matches_pyproject() -> None:
    pyproject = PYPROJECT.read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, re.MULTILINE)
    assert match, "pyproject.toml must declare a project version"
    note = DOCS_NOTE.read_text(encoding="utf-8")
    assert f'version = "{match.group(1)}"' in note


def test_install_sh_stays_free_of_version_logic() -> None:
    assert "VERSION" not in INSTALL_SH.read_text(encoding="utf-8")


def test_version_path_literal_lives_only_in_note() -> None:
    hits = _git_grep_paths(VERSION_PATH_LITERAL)
    assert hits, "the note must keep carrying the irreproducible-caliber explanation"
    note_rel = DOCS_NOTE.relative_to(ROOT).as_posix()
    assert set(hits) == {note_rel}


def test_module_makes_no_untracked_file_existence_claims() -> None:
    source = Path(__file__).read_text(encoding="utf-8")
    assert RUNS_DIR_MARK not in source
    assert RUNS_DIR_NAME not in source
